// Courtesy of https://twitter.com/lrgmnn/status/813635533658144768/
export const cards = [
  'Sleve McDichael',
  'Onson Sweemey',
  'Darryl Archideld',
  'Anatoli Smorin',
  'Rey McSriff',
  'Glenallen Mixon',
  'Mario McRlwain',
  'Raul Chamgerlain',
  'Kevin Nogilny',
  'Tony Smehrik',
  'Bobson Dugnutt',
  'Willie Dustice',
  'Jeromy Gride',
  'Scott Dourque',
  'Shown Furcotte',
  'Dean Wesrey',
  'Mike Truk',
  'Dwigt Rortugal',
  'Tim Sandaele',
  'Karl Dandleton',
  'Mike Sernandez',
  'Todd Bonzalez',
];
