# cribbed from test-dapp-card-store.yml from agoric-sdk
# TODO: cache node modules

name: Test Dapp Card Store

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
    - name: Checkout agoric-sdk
      uses: actions/checkout@v2
      with:
        repository: Agoric/agoric-sdk
        path: agoric-sdk
    - name: yarn install
      run: yarn install
      working-directory: ./agoric-sdk
    - name: yarn build
      run: yarn build
      working-directory: ./agoric-sdk
    - name: yarn link
      run: |
        yarn link-cli ~/bin/agoric
        echo "/home/runner/bin" >> $GITHUB_PATH
      working-directory: ./agoric-sdk

    - name: Check out dapp
      uses: actions/checkout@v2
      with:
        path: dapp
    - name: Agoric install in dapp
      run: agoric install
      working-directory: ./dapp
    - name: yarn build in dapp
      run: yarn build
      working-directory: ./dapp

    - name: Publish
      uses: netlify/actions/cli@master
      # https://github.com/netlify/actions/tree/master/cli
      with:
        args: deploy --dir=dapp/ui/dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
